name: Argon
on: [pull_request]
jobs:
  scan:
    name: Argon
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # origin: v2.3.5
      - name: Argon Security
        uses: argonsecurity/scanner-action@cb7009df51790cede644c59211e436c5f3805f87 # origin: v1.0
        with:
          should-notify: true
          argon-token: "${{ secrets.ARGON_TOKEN }}"