name: Argon
on: [pull_request]
jobs:
  scan:
    name: Argon
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Argon Security
        uses: argonsecurity/scanner-action@v1.0
        with:
          should-notify: true
          argon-token: "${{ secrets.ARGON_TOKEN }}"