name: Argon-Scanner
on: [pull_request]
jobs:
  scan:
    name: Argon Scanner
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Run Argon Scanner
        uses: docker://argonsecurity/scanner:github
        env:
          ARGON_SCANNER: https://demo-actions.argon.io
        with:
          should-notify: true
          argon-token: "${{ secrets.ARGON_TOKEN }}"
